apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: kk1 
spec:
  type: ClusterIP
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 80
      targetPort: 11434