apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: kk1 
spec:
  type: LoadBalancer
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080